### ISSUE TITLE
[Error] Update in ESP8266HTTPClient library made library unusable

### ISSUE THREAD

**Issue by Wirgiliusz** [karoldus/ESP8266IFTTTWebhook#1]
Since the change in ESP8266HTTPClient library it is required to give additional argument to http.begin() function: now it also requires WiFiClient object in addition to url String (see picture below)
![begin_error](https://user-images.githubusercontent.com/29927094/142876087-38823bc1-e94c-44b4-9244-ce04270ffba9.png)

**Comment by Wirgiliusz** [comment]
Fixed in #2

**Comment by karoldus** [comment]
Thanks!
